version: '3.4'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    networks:
      - nodenetwork
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    command: "dockerize -wait tcp://db:3306 -timeout 20s sh /usr/bin/docker-entrypoint.sh"
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    networks:
      - nodenetwork
    volumes:
      - ./docker/mysql/var:/var/lib/mysql
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    networks:
      - nodenetwork
    tty: true  
    ports:
      - 8080:80  
    depends_on:
      - db
      - app


volumes:
  node_modules:
networks:
  nodenetwork:
    driver: bridge